import {
  Avatar,
  Box,
  Center,
  Container,
  Group,
  List,
  Loader,
  SimpleGrid,
  Text,
  ThemeIcon,
} from "@mantine/core";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { CircleDashed } from "tabler-icons-react";
import { apiClient } from "../api/client";

const InvestorDetails = () => {
  const [idt, setInvestorDetails] = useState<InvestorDetails>();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const nav = useNavigate();

  const { id } = useParams();
  const getDetails = () => {
    setLoading(true);
    apiClient
      .get<InvestorDetails>("/investor/details/" + id)
      .then((res) => {
        console.log(res);

        setInvestorDetails(res.data);
        setError(false);
      })
      .catch((err) => {
        setError(true);
        console.log(err);
      })
      .finally(() => {
        setLoading(false);
      });
  };
  useEffect(() => {
    getDetails();
  }, []);

  if (loading)
    return (
      <Center style={{ height: "100vh" }}>
        <Loader color="dark" size="xl" />
      </Center>
    );
  if (error) return <div>Error (see console)</div>;
  return (
    <Container size="md" mt={20}>
      <div>
        <Group style={{ justifyContent: "space-between" }} align="flex-start">
          <Group spacing="md" align="flex-start">
            <Avatar
              size={150}
              src={idt?.investor.pfpURL}
              radius="md"
              alt="logo"
            />
            <div>
              <Text style={{ fontSize: "50px" }} weight={900}>
                {idt?.investor.displayName}
              </Text>
              <Text size="md" mb={25}>
                <a href={`mailto:${idt?.investor.contactEmail}`}>
                  {idt?.investor.contactEmail}
                </a>
              </Text>
            </div>
          </Group>
        </Group>
      </div>
      <SimpleGrid
        mt={15}
        breakpoints={[
          { minWidth: "sm", cols: 1 },
          { minWidth: "md", cols: 2 },
        ]}
      >
        <Group align="flex-start">
          <Text>{idt?.investor.shortDesc}</Text>
        </Group>
        <Box>
          <Text size="xl" weight={600} color="orange" mb={20}>
            Major Investments
          </Text>
          <List
            spacing="xs"
            size="sm"
            center
            icon={
              <ThemeIcon color="blue" size={24} radius="xl">
                <CircleDashed size={16} />
              </ThemeIcon>
            }
          >
            {idt?.investor.investedIn &&
              idt?.investor.investedIn
                .split(",")
                .map((itm, idx) => <List.Item key={idx}>{itm}</List.Item>)}
          </List>
        </Box>
      </SimpleGrid>
    </Container>
  );
};
export default InvestorDetails;
export interface startupDetails {
  id: number;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  startup: Startup;
}

export interface Startup {
  id: number;
  displayName: string;
  website: string;
  userId: number;
  contactEmail: string;
  shortDesc: string;
  amountRaised: string;
  ytURL: string;
  logoURL: string;
  revenue: number;
  profit: number;
}
// Generated by https://quicktype.io

export interface InvestorDetails {
  id: number;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  investor: Investor;
}

export interface Investor {
  id: number;
  displayName: string;
  contactEmail: string;
  shortDesc: string;
  iType: string;
  investedIn: string;
  pfpURL: string;
  userId: number;
}

