import { Center, Container, Loader, Text } from "@mantine/core";
import { useContext, useEffect, useState } from "react";
import { apiClient } from "../api/client";
import InvestorItem from "../components/InvestorItem";
import { AuthContext } from "../context/authContext";

const Investors = () => {
  const { state: authState } = useContext(AuthContext);

  const [investors, setInvestors] = useState<InvestorsT[]>([]);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    apiClient
      .get<InvestorsT[]>("investor")
      .then((res) => {
        setInvestors(res.data);
      })
      .catch((err) => {
        console.log(err);
        setError(true);
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading)
    return (
      <Center style={{ height: "100vh" }}>
        <Loader color="dark" size="xl" />
      </Center>
    );
  if (error)
    return (
      <Center style={{ height: "100vh" }}>
        <Text size="xl"> Someting went wrong. </Text>
      </Center>
    );

  return (
    <Container size="md">
      <Center my={20}>
        <Text weight={700} style={{ fontSize: "35px" }}>
          Investors
        </Text>
      </Center>
      <div>
        {investors.map((inverstor) => {
          return (
            <InvestorItem
              {...inverstor}
              startupUserId={authState.userId}
              key={inverstor.id}
            />
          );
        })}
      </div>
    </Container>
  );
};

export default Investors;

// Generated by https://quicktype.io

export interface InvestorsT {
  id: number;
  displayName: string;
  contactEmail: string;
  shortDesc: string;
  iType: string;
  investedIn: string;
  pfpURL: string;
  userId: number;
}

